spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/cafe?useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000